name: Run Gradle Tests

on:
  push:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java 
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Set run permissions for gradlew
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew test 
    
